name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas, no minuto 0
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Passo para criar o diretório 'dist' se não existir
      - name: Create output directory
        run: mkdir -p dist  # Cria o diretório 'dist'

      # Snake Animation
      - uses: Platane/snk@v2  # Usando versão estável
        id: snake-gif
        with:
          github_user_name: MatheusMalaquias
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Passo para criar a branch 'output' se não existir
      - name: Create 'output' branch if it doesn't exist
        run: |
          git fetch origin
          git checkout --orphan output
          git rm -rf .
          git commit --allow-empty -m "Create output branch"
          git push origin output

      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
